preset: symfony

risky: false

linting: true

#https://styleci.readme.io/v1.0/docs/presets
enabled:
  - short_array_syntax
  - align_double_arrow
disabled:
  - unalign_double_arrow
  - phpdoc_type_to_var

finder:
  exclude:
    - "tests"
    - "Resources"
    - "bin"
    - "var"
    - "vendor"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
